####################################
# YoloV5模型权重路径
weight:  "weights/vds_improve.pt"
# 输入图像的尺寸
input_size: 640
# 类别个数
class_num:  6
# 标签名称
class_name: ['Early-Turning', 'Green', 'Late-Turning', 'Red', 'Turning', 'White']
# 阈值设置
threshold:
  iou: 0.45
  confidence: 0.6
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: '0'
